/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(head.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3d732433335379aa562d2f31c46cdcb6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/txid/head.h>
// pydoc.h is automatically generated in the build directory
#include <head_pydoc.h>

void bind_head(py::module& m)
{

    using head    = gr::txid::head;


    py::class_<head, gr::block, gr::basic_block,
        std::shared_ptr<head>>(m, "head", D(head))

        .def(py::init(&head::make),
           py::arg("sizeof_stream_item"),
           py::arg("nitems"),
           py::arg("blocking"),
           D(head,make)
        )
        



        ;




}








