/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(packet_isolator_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f501bba5b4a4bc25aa016e009e067ee4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/txid/packet_isolator_c.h>
// pydoc.h is automatically generated in the build directory
#include <packet_isolator_c_pydoc.h>

void bind_packet_isolator_c(py::module& m)
{

    using packet_isolator_c    = gr::txid::packet_isolator_c;


    py::class_<packet_isolator_c, gr::block, gr::basic_block,
        std::shared_ptr<packet_isolator_c>>(m, "packet_isolator_c", D(packet_isolator_c))

        .def(py::init(&packet_isolator_c::make),
           py::arg("payload_length") = 0,
           py::arg("preamble_length") =  80,
           py::arg("lookup_window") =  30,
           py::arg("tag_name") =  "corr_est",
           D(packet_isolator_c,make)
        )
        



        ;




}








